src/Entity/ContentListProduct.php
<?php

namespace App\Entity;

use App\Repository\ContentListProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContentListProductRepository::class)]
class ContentListProduct
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: ListProduct::class, inversedBy: 'contentListProducts')]
    #[ORM\JoinColumn(nullable: false)]
    private $listProduct;

    #[ORM\ManyToOne(targetEntity: Product::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $product;

    #[ORM\Column(type: 'integer')]
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getListProduct(): ?ListProduct
    {
        return $this->listProduct;
    }

    public function setListProduct(?ListProduct $listProduct): self
    {
        $this->listProduct = $listProduct;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTotal()
    {
        return $this->product->getPrice() * $this->getQuantity();
    }
}

templates/customer/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    </head>
    <body>
        {% include "customer/shared/_navbar.html.twig" %}
        {% block body %}{% endblock %}
        {% include "customer/shared/_footer.html.twig" %}
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

templates/customer/home.html.twig
{% extends 'customer/base.html.twig' %}

{% block body %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 imageCarousel" src="https://images.unsplash.com/photo-1576491110919-df70d852860f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8c2hvZSUyMHNob3B8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" alt="Nike Dunk Low">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 imageCarousel" src="https://images.unsplash.com/photo-1567958528086-8d8324137918?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fHNob2UlMjBzaG9wfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="Nike Dunk Low Bordeaux">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 imageCarousel" src="https://images.unsplash.com/photo-1635855374289-b6ca7fe114ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fHNob2UlMjBzaG9wfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

 <section class="bg-secondary">
    <div class="container py-5">
    <div class="row">
          <div class="col-12">
            <h3 class="text-center text-white">Les catégories</h3>
          </div>  

          {% for category in categories %}

              <div class="col-sm-12 col-md-6 col-lg-4 mt-3 cat">

                  <div class="card">
                      <img src="{{ category.image }}" class="card-img-top imageCard" alt="image_category">
                      <div class="card-body">
                          <h5 class="card-title">{{ category.name }}</h5>
                          <a href="{{ path('boutique_product_show_by_category',{'id':category.id}) }}" class="btn btn-primary w-100">Consulter</a>
                      </div>
                  </div>
          
              </div>
              
          {% endfor %}

      </div>
    </div>
  </section>

  <section class="newProducts">
  <div class="container py-5">
      <div class="row">
        <div class="col-12">
          <h3 class="text-center">Les nouveautés</h3>
        </div>  

        {% for product in products %}

            <div class="col-sm-12 col-md-6 col-lg-4 mt-3">

                <div class="card">
                    <img src="{{ product.image }}" class="card-img-top imageCard" alt="image_category">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p>{{ product.price | priceEuro }}</p>
                        <a href="{{ path('boutique_product_detail',{'id':product.id}) }}" class="btn btn-primary w-100">Consulter</a>
                    </div>
                </div>
        
            </div>
            
        {% endfor %}

    </div>
     </div>
  </section>

{% endblock %}

templates/customer/panier.html.twig
{% extends "customer/base.html.twig" %}

{% block body %}

    <section>
        <div class="container py-5">
            <div class="row">
                <div class="col-12 mb-3">
                    <h3 class="text-center">Les produits du panier</h3>
                </div>
                {% include "_messages_flash.html.twig" %}
                <div class="col-12 mb-3">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Produit</th>
                                <th scope="col">Prix Unitaire</th>
                                <th scope="col">Quantité</th>
                                <th scope="col">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in detailProducts %}
                                <tr>
                                    <th>
                                        <div class="d-flex align-items-center">
                                            <img src="{{ item.product.image }}" alt="" style="height:80px;object-fit:contain;">
                                            <div class="d-flex flex-column align-items-center">
                                                <p>{{ item.product.name }}</p>
                                                <a class="btn btn-link text-danger" href="{{ path('cart_remove_product',{'id': item.product.id }) }}">Supprimer</a>
                                            </div>
                                           
                                        </div>
                                    </th>
                                    <td>{{ item.product.price | priceEuro }}</td>
                                    <td>
                                        <a class="btn btn-primary" href="{{ path('cart_decrement_product',{'id' : item.product.id }) }}"><i class="fas fa-minus-circle"></i></a>
                                        <button class="btn btn-light"> {{ item.qty }}</button>
                                        <a class="btn btn-primary" href="{{ path('cart_add',{'id' : item.product.id }) }}?routeToRedirect=panier"><i class="fas fa-plus-circle"></i></a>
                                    </td>
                                    <td>{{ item.total | priceEuro }}</td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <th colspan="2">
                                </th>
                                <th>
                                    <p><strong>Sous total</strong></p>
                                </th>
                                <th>
                                    <p><strong>{{ totalPrixPanier | priceEuro}}</strong></p>
                                </th>
                            </tr>
                            
                        
                        </tbody>
                    </table>
                </div>
                <div class="col-12 d-flex justify-content-end">
                    <a href="{{ path('boutique_commande_recap') }}" class="btn btn-success">Valider le panier</a>
                </div>
            </div>
        </div>
    </section>

{% endblock %}